# ---------- Base image ----------
FROM postgis/postgis:latest

# ---------- Install postgis utilities ----------
    RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    gdal-bin \
    && rm -rf /var/lib/apt/lists/*

COPY ./meteomate_postgis/data/* /tmp/